# Generated by Django 4.2.4 on 2025-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='processed_text',
            field=models.TextField(blank=True),
        ),
    ]
