# Generated by Django 4.2.4 on 2025-05-27 21:21

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_analysisresult_processed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='processed_text',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='entities',
            field=models.JSONField(default=list, encoder=json.encoder.JSONEncoder),
        ),
    ]
