# Generated by Django 4.2.4 on 2025-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_analysisresult_processed_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='morph_analysis',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='entities',
            field=models.JSONField(default=list),
        ),
    ]
